version: 8

finder:
  path:
    - 'packages/framework'
    - 'packages/skeleton'
    - 'packages/sprinkle-account'
    - 'packages/sprinkle-admin'
    - 'packages/sprinkle-core'
  exclude:
    - "tests"
  name: "*.php"
  not-name:
    - "*Stub.php"
    - "*Test.php"

enabled:
  - concat_with_spaces

disabled:
  - concat_without_spaces