name: Build

on:
    push:
        branches: ['*']
    pull_request:
        branches: ['*']
    workflow_dispatch:
    # schedule:
    # - cron: "0 0 * * 5"

jobs:
    Vite:
        strategy:
            fail-fast: false
            matrix:
                node_versions: [18, 20]

        runs-on: ubuntu-latest
        name: Vite - Node ${{ matrix.node_versions }}

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node_versions }}

            - name: Install Dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Test
              run: npm run coverage
      
            - name: Upload coverage to Codecov
              if: github.event_name != 'schedule'
              uses: codecov/codecov-action@v4
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                file: ./_meta/_coverage/clover.xml
                fail_ci_if_error: true
