name: Frontend

on:
    push:
        branches: [6.0]
        paths:
            - packages/skeleton
            - packages/sprinkle-account
            - packages/sprinkle-admin
            - packages/sprinkle-core
            - packages/theme-pink-cupcake
    pull_request:
        branches: [6.0]
    workflow_dispatch:

jobs:
    Build:
        strategy:
            fail-fast: false
            matrix:
                node_versions: [18, 20]

        runs-on: ubuntu-latest
        name: Skeleton Build - Node ${{ matrix.node_versions }}

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node_versions }}

            - name: Install Dependencies
              run: npm ci

            - name: Test
              run: npm run --workspace=userfrosting vite:build

    Coverage:
        strategy:
            fail-fast: false
            matrix:
                node_versions: [18, 20]

        runs-on: ubuntu-latest
        name: Test & Coverage - Node ${{ matrix.node_versions }}

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node_versions }}

            - name: Install Dependencies
              run: npm ci

            - name: Test
              run: npm run coverage
      
            - name: Upload coverage to Codecov
              if: github.event_name != 'schedule'
              uses: codecov/codecov-action@v5
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                files: ./_meta/_coverage/clover.xml
                fail_ci_if_error: true

    Prettier:
        runs-on: ubuntu-latest
        name: Code Style Check

        steps:
            - uses: actions/checkout@v4

            - name: Prettier dry run
              uses: creyD/prettier_action@v4.3
              with:
                  dry: True
                  prettier_options: --check packages/**/app/assets/**/*.* packages/theme-pink-cupcake/src/**/*.*