name: Monorepo Split

on:
  push:
    # Only trigger for specific branches or changes in specific paths.
    branches:
      - "*"
    # paths:
    #   - packages/**
    tags:
      - "*"

jobs:
    sync_commits:
        runs-on: ubuntu-latest
        name: Sync commits
        # Execute this workflow job only on the main repository.
        if: github.repository == 'userfrosting/monorepo'
        steps:
            - uses: actions/checkout@v4
              with:
                  persist-credentials: false
                  fetch-depth: 0

            # Add a personal access token to the repository secrets. This will allow the splitter action to push the new commits
            - uses: frankdejonge/use-github-token@1.0.2
              with:
                  authentication: "username:${{ secrets.ACCESS_TOKEN }}"
                  user_name: "UserFrosting Bot"
                  user_email: "no-reply@userfrosting.com"

            # Cache the splitsh executable to speedup future runs
            - name: Cache splitsh-lite
              id: splitsh-cache
              uses: actions/cache@v4
              with:
                  path: "./.splitsh"
                  key: '${{ runner.os }}-splitsh-d-101'

            # Sync commits and tags for the configured subtree splits
            - uses: frankdejonge/use-subsplit-publish@1.1.0
              with:
                source-branch: '6.0'
                config-path: '.github/subtree-splitter-config.json'
                splitsh-path: './.splitsh/splitsh-lite'
                splitsh-version: 'v1.0.1'
