name: Monorepo Split

on:
  push:
    branches: ['*']
    tags: ['*']
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
    packages_split:
        runs-on: ubuntu-latest
        name: Split Monorepo - ${{ matrix.package.name }}

        strategy:
            fail-fast: false
            matrix:
                package:
                    - name: "Pink Cupcake"
                      local_path: "packages/ui/theme-pink-cupcake"
                      split_repository: "theme-pink-cupcake"
                      branch: "main"

        steps:
            - uses: actions/checkout@v2

            # no tag
            - if: "!startsWith(github.ref, 'refs/tags/')"
              uses: "symplify/monorepo-split-github-action@2.3"
              with:
                  package_directory: "${{ matrix.package.local_path }}"
                  repository_organization: "userfrosting"
                  repository_name: "${{ matrix.package.split_repository }}"
                  user_name: "UserFrosting Bot"
                  user_email: "no-reply@userfrosting.com"
                  branch: "${{ matrix.package.branch }}"

            # with tag
            - if: "startsWith(github.ref, 'refs/tags/')"
              uses: "symplify/monorepo-split-github-action@2.3"
              with:
                  tag: ${GITHUB_REF#refs/tags/}
                  package_directory: "${{ matrix.package.local_path }}"
                  repository_organization: "userfrosting"
                  repository_name: "${{ matrix.package.split_repository }}"
                  user_name: "UserFrosting Bot"
                  user_email: "no-reply@userfrosting.com"
                  branch: "${{ matrix.package.branch }}"