name: Build

on:
    push:
        branches: ['*']
    pull_request:
        branches: ['*']
    workflow_dispatch:

jobs:
    Prettier:
        runs-on: ubuntu-latest
        name: Code Style Check

        steps:
            - uses: actions/checkout@v4

            - name: Prettier dry run
              uses: creyD/prettier_action@v4.3
              with:
                  dry: True
